'use strict';

const assert = require('assert');
const cp = require('child_process');
const fs = require('fs');
const path = require('path');

describe('test/build_contract.test.js', () => {
  it('should build the cli runtime without changing the entrypoint contract', () => {
    const npmCommand = process.platform === 'win32' ? 'npm.cmd' : 'npm';
    const eslintCommand = path.join(__dirname, '..', 'node_modules', '.bin', process.platform === 'win32' ? 'eslint.cmd' : 'eslint');

    cp.execFileSync(npmCommand, [ 'run', 'build' ], {
      cwd: path.join(__dirname, '..'),
      encoding: 'utf8',
      stdio: 'pipe',
    });
    cp.execFileSync(eslintCommand, [ 'lib/program.js' ], {
      cwd: path.join(__dirname, '..'),
      encoding: 'utf8',
      stdio: 'pipe',
    });

    const helpOutput = cp.execFileSync(process.execPath, [ path.join(__dirname, '../bin/projj.js') ], {
      cwd: path.join(__dirname, '..'),
      encoding: 'utf8',
    });

    assert(/Usage: \[command\] \[options]/.test(helpOutput));
  });

  it('should rebuild generated command runtime files from source', () => {
    const repoRoot = path.join(__dirname, '..');
    const npmCommand = process.platform === 'win32' ? 'npm.cmd' : 'npm';
    const sourceCommandDir = path.join(repoRoot, 'src', 'command');
    const files = [
      path.join(repoRoot, 'lib/base_command.js'),
      ...fs.readdirSync(sourceCommandDir)
        .filter(file => file.endsWith('.ts'))
        .map(file => path.join(repoRoot, 'lib', 'command', file.replace(/\.ts$/, '.js'))),
    ];
    const backups = new Map(
      files
        .filter(file => fs.existsSync(file))
        .map(file => [ file, fs.readFileSync(file, 'utf8') ])
    );

    try {
      files.forEach(file => fs.rmSync(file, { force: true }));

      cp.execFileSync(npmCommand, [ 'run', 'build' ], {
        cwd: repoRoot,
        encoding: 'utf8',
        stdio: 'pipe',
      });

      files.forEach(file => {
        assert(fs.existsSync(file), `${path.relative(repoRoot, file)} should be regenerated by build`);
      });
    } finally {
      files.forEach(file => {
        if (!fs.existsSync(file) && backups.has(file)) {
          fs.writeFileSync(file, backups.get(file), 'utf8');
        }
      });
    }
  });
});
